In [14]:
# copy the data from the exercise
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [3]:
# problem1
# How many negative numbers are there?
len(a[a<0])

4

In [4]:
# problem 2
# How many positive numbers are there?
len(a[a>0])

5

In [5]:
# problem3
# How many even positive numbers are there?
a[(a>0) & (a%2==0)]

array([ 4, 10, 12])

In [6]:
# problem4
# If you were to add 3 to each data point, how many positive numbers would there be?
len(a[(a+3)>0])

10

In [7]:
# problem 5
# If you squared each number, what would the new mean and standard deviation be?
(a**2)
(a**2).mean()

74.0

In [8]:
# problem 5
# find standard deviation
(a**2).std()

144.0243035046516

In [68]:
# find the centering
# A common statistical operation on a dataset is centering
a-(a.mean())

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [9]:
# calculate z score
# z-score
(a-a.mean())/a.std()

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [2]:
# question 8
import numpy as np
# Life w/o numpy to life with numpy
## Setup 1
a =[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:


In [11]:
# exercise 8-1

In [17]:
# sum all numbers
def sum_of_a(a):
    a=sum(a)
    return a
sum_of_a(a)

55

In [18]:
# exercise 8-2

In [20]:
# find minimum
def min_of_a (a):
    a=min(a)
    return a
min_of_a(a)

1

In [22]:
# exercise 8-3

In [24]:
# find max value
def max_of_a(a):
    a=max(a)
    return a
max_of_a(a)

10

In [25]:
# exercise 8-4
# find mean of a

In [35]:
def mean_of_a(a):
    a= sum(a)/10
    return a
mean_of_a(a)

5.5

In [37]:
# exercise 8-5
# find product of_a

In [47]:
def product_of_a(a):
    b=1
    for num in a:
        b=b*num
    return b
product_of_a(a)

3628800

In [48]:
# exercise 8-6
# find square of a

In [ ]:
def squares_of_a(a):
        return [num**2 for num in a]
squares_of_a(a)

In [61]:
# exercise 8-7
# find odds in a list

In [4]:
def odds_in_a(a):
    b=[]
    for num in a:
        if num%2==1:
            b.append(num)  
    return b
odds_in_a(a)

[1, 3, 5, 7, 9]

In [6]:
# problem 8-8
# find even number in the list

In [8]:
def odds_in_a(a):
    b=[]
    for num in a:
        if num%2==0:
            b.append(num)  
    return b
odds_in_a(a)

[2, 4, 6, 8, 10]

In [32]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
    ]
b_ar=np.array(b)

In [34]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
    
b_ar.sum()

33

In [36]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  
b_ar.min()

3

In [37]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
b_ar.max()

8

In [39]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
b_ar.mean()

5.5

In [41]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
b_ar.prod()

20160

In [48]:
import math
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

np.square(b_ar)

array([[ 9, 16, 25],
       [36, 49, 64]])

In [49]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
            
b_ar[b_ar%2==1]

array([3, 5, 7])

In [50]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
            
b_ar[b_ar%2==0]

array([4, 6, 8])

In [52]:
# Exercise 9 - print out the shape of the array b.
b_ar.shape

(2, 3)

In [55]:
# Exercise 10 - transpose the array b.
b_ar.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

In [57]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
b_ar.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [58]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
b_ar.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [60]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
c_ar=np.array(c)

In [64]:
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.
c_ar.max(),c_ar.min(),c_ar.sum(),c_ar.prod()

(9, 1, 45, 362880)

In [65]:
# Exercise 2 - Determine the standard deviation of c.
c_ar.std()

2.581988897471611

In [66]:
# Exercise 3 - Determine the variance of c.
c_ar.var()

6.666666666666667

In [68]:
# Exercise 4 - Print out the shape of the array c
c_ar.shape

(3, 3)

In [69]:
# Exercise 5 - Transpose c and print out transposed result.
c_ar.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [71]:
# Exercise 6 - Get the dot product of the array c with c. 
c_ar.dot(c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [86]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
np.sum(c*c_ar.transpose())

261

In [88]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
np.prod(c_ar*c_ar.transpose())

131681894400

In [89]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d_ar=np.array(d)

In [91]:
# Exercise 1 - Find the sine of all the numbers in d
np.sin(d_ar)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [92]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d_ar)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [93]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d_ar)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [95]:
# Exercise 4 - Find all the negative numbers in d
d_ar[d_ar<0]

array([-90, -30, -45, -45])

In [96]:
# Exercise 5 - Find all the positive numbers in d
d_ar[d_ar>0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [98]:
# Exercise 6 - Return an array of only the unique numbers in d.
np.unique(d_ar)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [99]:
# Exercise 7 - Determine how many unique numbers there are in d.
len(np.unique(d_ar))

11

In [100]:
# Exercise 8 - Print out the shape of d.
d_ar.shape

(3, 6)

In [105]:
# Exercise 9 - Transpose and then print out the shape of d.
(d_ar.transpose()).shape

(6, 3)

In [106]:
# Exercise 10 - Reshape d into an array of 9 x 2
d_ar.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])